apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: be-base
  labels:
    version: v1
    app: zipkin
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: zipkin
  name: zipkin-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      version: v1
      app: zipkin
      app.kubernetes.io/version: v1
      app.kubernetes.io/name: zipkin
  template:
    metadata:
      labels:
        version: v1
        app: zipkin
        app.kubernetes.io/version: v1
        app.kubernetes.io/name: zipkin
    spec:
      containers:
        - name: container-zipkin
          imagePullPolicy: IfNotPresent
          image: openzipkin/zipkin:2.23-amd64
          ports:
            - name: http-9411
              protocol: TCP
              containerPort: 9411
          resources:
            requests:
              cpu: '50m'
              memory: 200Mi
            limits:
              cpu: '200m'
              memory: 500Mi
          # env:
          #   - name: STORAGE_TYPE
          #     value: elasticsearch
          #   - name: ES_HOSTS
          #     value: 'elasticsearch.be-base:9200'
      nodeSelector:
        app.kubernetes.io/name: tx-master01
      serviceAccount: default
      affinity: {}
      initContainers: []
      volumes: []
      imagePullSecrets: null
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  namespace: be-base
  labels:
    version: v1
    app: zipkin
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: zipkin
  name: zipkin
spec:
  sessionAffinity: None
  selector:
    app: zipkin
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: zipkin
  ports:
    - name: http-9411
      protocol: TCP
      port: 9411
      targetPort: 9411
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: zipkin-ingress
  namespace: be-base
  labels:
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: zipkin
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - zipkin.ihave.cool
      secretName: zipkin-tls
  rules:
    - host: zipkin.ihave.cool
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: zipkin
                port:
                  number: 9411
---
