apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-9200
      protocol: TCP
      port: 9200
      targetPort: http
    - name: http-9300
      protocol: TCP
      port: 9300
      targetPort: http
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
