apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "threekingdomsmeta.fullname" . }}
  namespace: {{ include "threekingdomsmeta.namespace" . }}
  labels:
    {{- include "threekingdomsmeta.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "threekingdomsmeta.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "threekingdomsmeta.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "threekingdomsmeta.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: {{ include "threekingdomsmeta.fullname" . }}-volume1
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            # - name: {{ include "threekingdomsmeta.fullname" . }}-volume2
            #   mountPath: /usr/share/nginx/html
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "threekingdomsmeta.fullname" . }}-volume1
          configMap:
            name: {{ include "threekingdomsmeta.fullname" . }}-config1
        # - name: {{ include "threekingdomsmeta.fullname" . }}-volume2
        #   hostPath:
        #     path: {{ .Values.htmlroot }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
