---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-prod
  namespace: kubesphere-monitoring-system
type: Opaque
stringData:
  # datasource: "exporter:zodancer_exporter@xxx.mysql.rds.aliyuncs.com:3306"
  datasource: "root:xxx@xxx.com:3306"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-exporter-prod
  name: mysql-exporter-prod
  namespace: kubesphere-monitoring-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter-prod
  template:
    metadata:
      labels:
        app: mysql-exporter-prod
    spec:
      containers:
      - env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret-prod
              key: datasource
        image: prom/mysqld-exporter
        imagePullPolicy: IfNotPresent
        name: mysql-exporter-prod
        ports:
        - containerPort: 9104
          name: metric-port 
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter-prod
  namespace: kubesphere-monitoring-system
  labels:
    app: mysql-exporter-prod
spec:
  type: ClusterIP
  # clusterIP: None
  selector:
    app: mysql-exporter-prod
  ports:
  - name: http-metrics
    port: 9104
    targetPort: 9104
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: mysql-service-monitor
  name: mysql
  namespace: kubesphere-monitoring-system
spec:
  endpoints:
  - interval: 30s
    port: http-metrics
  jobLabel: mysql
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: mysql-exporter-prod
---
