apiVersion: v1
kind: Service
metadata:
  name: {{ include "frp.fullname" . }}-api-nodeport
  labels:
    {{- include "frp.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 32001
      targetPort: http-api
      protocol: TCP
      name: http-api-nodeport
      nodePort: 32001
  selector:
    {{- include "frp.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frp.fullname" . }}-api
  labels:
    {{- include "frp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiService.type }}
  ports:
    - port: {{ .Values.apiService.port }}
      targetPort: http-api
      protocol: TCP
      name: http-api
  selector:
    {{- include "frp.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frp.fullname" . }}-dashboard
  labels:
    {{- include "frp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dashboardService.type }}
  ports:
    - port: {{ .Values.dashboardService.port }}
      targetPort: http-dashboard
      protocol: TCP
      name: http-dashboard
  selector:
    {{- include "frp.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frp.fullname" . }}-api-http-https
  labels:
    {{- include "frp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dashboardService.type }}
  ports:
    - port: 80
      targetPort: http-api-http
      protocol: TCP
      name: http-api-http
    - port: 443
      targetPort: http-api-https
      protocol: TCP
      name: http-api-https
  selector:
    {{- include "frp.selectorLabels" . | nindent 4 }}
