---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: prometheus-k8s
  namespace: kubesphere-monitoring-system
  labels:
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: kubesphere-monitoring-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubesphere.io/creator: admin
spec:
  tls:
    - hosts:
        - prometheus.zodance.com
      secretName: prometheus-tls
  rules:
    - host: prometheus.zodance.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: prometheus-k8s
                port:
                  number: 9090
---
