---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dianmei-spring-cloud
  namespace: dianmei-dev
spec:
  endpoints:
    - interval: 15s
      path: /actuator/prometheus
      port: http
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      micrometer-prometheus-discovery: 'true'
