---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yacd
spec:
  replicas: 1
  selector:
    matchLabels:
      # manage pods with the label app: yacd
      app: yacd
  template:
    metadata:
      labels:
        app: yacd
    spec:
      containers:
        - name: yacd
          image: haishanh/yacd:v0.3.8
          ports:
            - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: ali-node1
---
apiVersion: v1
kind: Service
metadata:
  name: yacd-svc
spec:
  ports:
    - name: http1
      port: 80
  selector:
    # apply service to any pod with label app: yacd
    app: yacd
---
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yacd-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - yacd.ihave.cool
      secretName: yacd-tls
  rules:
    - host: yacd.ihave.cool
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: yacd-svc
                port:
                  number: 80
{{- end }}
