---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dianmei-dev
  name: rabbitmq-pvc
  labels: {}
  annotations:
    kubesphere.io/alias-name: RabbitMQ存储
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: rabbitmq-ingress
  namespace: dianmei-dev
  labels:
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: rabbitmq-management
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubesphere.io/creator: admin
spec:
  tls:
    - hosts:
        - rabbitmq-dev.zodance.com
      secretName: rabbitmq-tls
  rules:
    - host: rabbitmq-dev.zodance.com
      http:
        paths:
          - path: /
            backend:
              serviceName: rabbitmq-management
              servicePort: 15672
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dianmei-dev
  labels:
    version: v1
    app: rabbitmq-management
  name: rabbitmq-management-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      version: v1
      app: rabbitmq-management
  template:
    metadata:
      labels:
        version: v1
        app: rabbitmq-management
      annotations:
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      containers:
        - name: container-nl2u3q
          imagePullPolicy: IfNotPresent
          image: 'rabbitmq:management'
          ports:
            - name: tcp-15671
              protocol: TCP
              containerPort: 15671
            - name: tcp-15672
              protocol: TCP
              containerPort: 15672
            - name: tcp-15691
              protocol: TCP
              containerPort: 15691
            - name: tcp-15692
              protocol: TCP
              containerPort: 15692
            - name: tcp-25672
              protocol: TCP
              containerPort: 25672
            - name: tcp-4369
              protocol: TCP
              containerPort: 4369
            - name: tcp-5671
              protocol: TCP
              containerPort: 5671
            - name: tcp-5672
              protocol: TCP
              containerPort: 5672
          resources:
            requests:
              cpu: '0.2'
              memory: 200Mi
            limits:
              cpu: '1'
              memory: 1000Mi
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: volume-5dzgzo
              readOnly: false
              mountPath: /var/lib/rabbitmq
      serviceAccount: default
      affinity: {}
      initContainers: []
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: host-time
        - name: volume-5dzgzo
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
      imagePullSecrets: null
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  serviceName: rabbitmq-management
---
apiVersion: v1
kind: Service
metadata:
  namespace: dianmei-dev
  labels:
    version: v1
    app: rabbitmq-management
  annotations:
    kubesphere.io/serviceType: statefulservice
    kubesphere.io/alias-name: rabbitmq-management
  name: rabbitmq-management
spec:
  sessionAffinity: None
  selector:
    app: rabbitmq-management
  ports:
    - name: tcp-15671
      protocol: TCP
      port: 15671
      targetPort: 15671
    - name: tcp-15672
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: tcp-15691
      protocol: TCP
      port: 15691
      targetPort: 15691
    - name: tcp-15692
      protocol: TCP
      port: 15692
      targetPort: 15692
    - name: tcp-25672
      protocol: TCP
      port: 25672
      targetPort: 25672
    - name: tcp-4369
      protocol: TCP
      port: 4369
      targetPort: 4369
    - name: tcp-5671
      protocol: TCP
      port: 5671
      targetPort: 5671
    - name: tcp-5672
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 31010
  type: NodePort

