---
apiVersion: v1
data:
  config.yaml: |+
    {
      "run_type": "client",
      "local_addr": "0.0.0.0",
      "local_port": 7890,
      "remote_addr": "116.163.10.237",
      "remote_port": 4563,
      "password": [
        "13ccf37d-ece5-395b-999e-b2c8ac94ef3f"
      ],
      "log_level": 1,
      "ssl": {
        "cert": "",
        "verify_hostname": false,
        "verify": false
      }
    }
kind: ConfigMap
metadata:
  name: trojan-conf
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trojan
spec:
  replicas: 1
  selector:
    matchLabels:
      # manage pods with the label app: trojan
      app: trojan
  template:
    metadata:
      labels:
        app: trojan
    spec:
      hostNetwork: true
      volumes:
        - name: trojan-conf-map
          configMap:
            name: trojan-conf
      containers:
        - name: trojan
          image: teddysun/trojan:1.16.0
          ports:
            - containerPort: 7890
          volumeMounts:
            - name: trojan-conf-map
              mountPath: /etc/trojan/config.json
              subPath: config.yaml
---

