Vagrant.configure("2") do |config|
   (1..3).each do |i|
        config.vm.define "k8s-node#{i}" do |node|
            # 设置虚拟机的Box
            node.vm.box = "centos7"
            # node.vm.box_url = "../Box/CentOS-7.box"

            # 设置虚拟机的主机名
            node.vm.hostname="k8s-node#{i}"

            # 设置虚拟机的IP
            node.vm.network "private_network", ip: "192.168.56.#{99+i}", netmask: "255.255.255.0"

            # 设置主机与虚拟机的共享目录
            # node.vm.synced_folder "./share/", "/home/vagrant/", mount_options: ["dmode=777", "fmode=777"]

            # VirtaulBox相关配置
            node.vm.provider "virtualbox" do |v|
                # 设置虚拟机的名称
                v.name = "k8s-node#{i}"
                # 设置虚拟机的内存大小
                # 设置虚拟机的CPU个数
                if i == 1
                  v.memory = 8192
                  v.cpus = 4
                else
                  v.memory = 4096
                  v.cpus = 2
                end
            end
        end
   end
end
