FROM elasticsearch:7.4.2
ADD elasticsearch-analysis-ik-7.4.2 /usr/share/elasticsearch/plugins/elasticsearch-analysis-ik-7.4.2
ADD elasticsearch-analysis-pinyin-7.4.2 /usr/share/elasticsearch/plugins/elasticsearch-analysis-pinyin-7.4.2
RUN chmod 777 /usr/share/elasticsearch/plugins
