apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: be-base
  name: elasticsearch-pvc
  labels: {}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: be-base
  labels: {}
  name: elastic-search-conf
spec:
  template:
    metadata:
      labels: {}
data:
  http.host: 0.0.0.0
  discovery.type: single-node
  ES_JAVA_OPTS: '-Xms64m -Xmx512m'
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: elasticsearch
  namespace: be-base
  labels:
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: elasticsearch
spec:
  selector:
    matchLabels:
      app.kubernetes.io/version: v1
      app.kubernetes.io/name: elasticsearch
  addOwnerRef: true
  componentKinds:
    - group: ''
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: extensions
      kind: Ingress
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: elasticsearch-ingress
  namespace: be-base
  labels:
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: elasticsearch
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - es.zodance.com
      secretName: es-tls
  rules:
    - host: es.zodance.com
      http:
        paths:
          - path: /
            backend:
              service:
                name: elasticsearch
                port:
                  number: 9200
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: be-base
  labels:
    version: v1
    app: elasticsearch
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: elasticsearch
  name: elasticsearch-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        version: v1
        app: elasticsearch
        app.kubernetes.io/version: v1
        app.kubernetes.io/name: elasticsearch
    spec:
      containers:
        - name: container-5zhs4u
          imagePullPolicy: IfNotPresent
          image: juck/es-ik-pinyin
          env:
            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: elastic-search-conf
                  key: ES_JAVA_OPTS
            - name: discovery.type
              valueFrom:
                configMapKeyRef:
                  name: elastic-search-conf
                  key: discovery.type
            - name: http.host
              valueFrom:
                configMapKeyRef:
                  name: elastic-search-conf
                  key: http.host
          ports:
            - name: http-9200
              protocol: TCP
              containerPort: 9200
              servicePort: 9200
            - name: http-9300
              protocol: TCP
              containerPort: 9300
              servicePort: 9300
          resources:
            requests:
              cpu: '0.2'
              memory: 500Mi
            limits:
              cpu: '2'
              memory: 2000Mi
          volumeMounts:
            - name: volume-0w9u7w
              readOnly: false
              mountPath: /usr/share/elasticsearch/data
      serviceAccount: default
      affinity: {}
      initContainers: []
      volumes:
        - name: volume-0w9u7w
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
      imagePullSecrets: null
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  serviceName: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  namespace: be-base
  labels:
    version: v1
    app: elasticsearch
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: elasticsearch
  name: elasticsearch
spec:
  sessionAffinity: None
  selector:
    app: elasticsearch
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: elasticsearch
  template:
    metadata:
      labels:
        version: v1
        app: elasticsearch
  ports:
    - name: http-9200
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: http-9300
      protocol: TCP
      port: 9300
      targetPort: 9300
  clusterIP: None
