apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: freenet
  labels:
    version: v1
    app: sub-web
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: sub-web
  name: sub-web-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      version: v1
      app: sub-web
      app.kubernetes.io/version: v1
      app.kubernetes.io/name: sub-web
  template:
    metadata:
      labels:
        version: v1
        app: sub-web
        app.kubernetes.io/version: v1
        app.kubernetes.io/name: sub-web
    spec:
      containers:
        - name: container-sub-web
          imagePullPolicy: IfNotPresent
          image: careywong/subweb:latest
          ports:
            - name: http-80
              protocol: TCP
              containerPort: 80
          # env:
          #   - name: STORAGE_TYPE
          #     value: elasticsearch
          #   - name: ES_HOSTS
          #     value: 'elasticsearch.freenet:9200'
      nodeSelector:
        kubernetes.io/hostname: racknerd-node1
      serviceAccount: default
      affinity: {}
      initContainers: []
      volumes: []
      imagePullSecrets: null
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  namespace: freenet
  labels:
    version: v1
    app: sub-web
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: sub-web
  name: sub-web
spec:
  sessionAffinity: None
  selector:
    app: sub-web
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: sub-web
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: 80
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: sub-web-ingress
  namespace: freenet
  labels:
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: sub-web
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - sub-web.uhave.cool
      secretName: sub-web-tls
  rules:
    - host: sub-web.uhave.cool
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: sub-web
                port:
                  number: 80
---
