apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheusalert.fullname" . }}
  namespace: {{ include "prometheusalert.namespace" . }}
  labels:
    {{- include "prometheusalert.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prometheusalert.selectorLabels" . | nindent 4 }}
