apiVersion: v1
kind: Service
metadata:
  name: api-dev
  namespace: local
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: api-dev
  namespace: local
subsets:
  - addresses:
      - ip: 100.64.0.6
    ports:
      - port: 8080
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: api-dev-ingress
  namespace: local
  labels:
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: api-dev
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
        - api-dev.ihave.cool
      secretName: zipkin-tls
  rules:
    - host: api-dev.ihave.cool
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: api-dev
                port:
                  number: 8080
---

